
spring:
  application:
    name: order-shopcar-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.252.115:3306/wx_shop
    username: root
    password: 2941@root
server:
  port: 8083