
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#          filters:
#          - StripPrefix=1
      routes:
        - id: goods
          uri: lb://goods-service
          predicates:
          - Path=/goods/**
server:
  port: 8849